### ISSUE TITLE
Broadcasted Operations Stall Julia

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaArrays/StaticArrays.jl#191] opened 2017-05-28 04:23 UTC
When broadcasting some operations, Julia will get stuck. Example:

```julia
using StaticArrays
u0 = @SMatrix rand(4,2)
reltol = 0.003
uprev = u0
u = u0
max.(abs.(u),abs.(uprev)) .* reltol
```

This is tested on the latest release (on v0.6-rc2) and on StaticArrays master.

**Comment by c42f** [comment] 2017-05-29 08:22
Yikes, I'm not sure what to make of this one yet.  More minimal test case:

```julia
using StaticArrays
x = broadcast((a,b,c)->0, SVector(1,1), 0, 0)
```

**Comment by andyferris** [comment] 2017-05-29 08:50
Oh dear. These should be our implementation of broadcast, I suppose.

**Comment by bshall** [comment] 2017-05-29 10:11
I think the issue is in the `broadcast_sizes` function. If you manually define the sizes @c42f example works
```julia
s = (Size{(2,)}(), Size(), Size())
StaticArrays._broadcast((a,b,c)->0, s, SVector(1,1), 0, 0)
```
But calling `StaticArrays.broadcast_sizes(SVector(1,1), 0, 0)` hangs.

**Comment by bshall** [comment] 2017-05-29 11:11
It seems like this could be a julia bug. A test case is
```julia
f(t::Tuple) = t
f(t::Tuple, a::Int, as...) = f((t..., a), as...)
f(t::Tuple, a::Float64, as...) = f((t..., a), as...)

f((), 1, 1, 1) # works fine
f((), 1.0, 1.0, 1.0) # works fine
f((), 1, 1.0, 1) # hangs
```
What do you guys think @andyferris @c42f is this a bug or is there something wrong with the recursion? As a workaround for `StaticArrays` you don't really need to define `broadcast_sizes` recursively, you could just loop over the `as` to build up the sizes.

**Comment by c42f** [comment] 2017-05-29 11:18
Yes, I was just coming to the same conclusion myself, I think this is a julia bug, at least in julia-0.6.0-rc2.

Unfortunately we can't use a simple loop, as we need this to be fully type inferred.  We might be able to get away with a carefully constructed generated function...

**Comment by bshall** [comment] 2017-05-29 11:23
I just checked on 0.5.1 and it also doesn't work there. Should I go ahead and report it?

> Unfortunately we can't use a simple loop, as we need this to be fully type inferred

Oh right, that makes sense.

**Comment by andyferris** [comment] 2017-05-29 11:24
This is a bit odd. This is v0.6-rc2?

I know @vtjnash has been going on a mission lately to remove the "collector" pattern from `Base` because it doesn't interact with well with inference. See e.g. https://github.com/JuliaLang/julia/pull/22019.

An example on how to this pattern correctly is here:

https://github.com/JuliaLang/julia/pull/22019/files#diff-2264bb51acec4e7e2219a3cb1c733651R206

It's important that types going to the inner functions are getting simpler (smaller tuples) not more complex (longer tuples). One "better" way to do our trivial `f` is:

```julia
f(a::Int, as...) = (a, f(as...)...)
f(a::Float64, as...) = (a, f(as...)...)
```
Note that the inner function has one less argument than the outer, so inference can feel safe that types are getting simpler. We should make *StaticArrays* adhere to such patterns, rather than the collector one.

**Comment by c42f** [comment] 2017-05-29 11:36
Ok, nice that makes a lot of sense.

This is still a bug but the workaround seems easy.

**Comment by c42f** [comment] 2017-05-29 11:40
PR coming.

**Comment by bshall** [comment] 2017-05-29 11:44
I've got it working if you'd like me to do it?

**Comment by c42f** [comment] 2017-05-29 11:46
Sure, push it up if you like. I've got it working locally but I was just refactoring to beef up the broadcast tests.

**Comment by andyferris** [comment] 2017-05-29 11:50
I like the competition. :)

**Comment by c42f** [comment] 2017-05-29 12:13
Hah, I should be working on my logging package instead, given juliacon is nearly on us.  @bshall has kindly agreed to finish it off :-)

**Comment by c42f** [comment] 2017-05-30 10:16
Fixed in #196

**Closed by c42f** 2017-05-30 10:16 UTC

**Comment by ChrisRackauckas** [comment] 2017-06-06 05:24
Hey, is there a plan to tag StaticArrays anytime soon? I am wondering since this is making tests fail in DiffEq on v0.6, and I was hoping to get some updates in before JuliaCon.

**Comment by andyferris** [comment] 2017-06-06 06:20
Sure - why not?

**Comment by andyferris** [comment] 2017-06-06 06:27
https://github.com/JuliaArrays/StaticArrays.jl/releases/tag/v0.5.1

**Comment by ChrisRackauckas** [comment] 2017-06-06 06:28
Thanks!

**Comment by andyferris** [comment] 2017-06-06 06:30
I haven't heard from @attobot yet...

**Comment by andyferris** [comment] 2017-06-06 06:34
Hmm... @JuliaArrays didn't have @attobot enabled for StaticArrays...

**Comment by andyferris** [comment] 2017-06-06 06:41
@simonbyrne how do I get attobot to pick up a release I've already made? And has github removed the ability to delete a release? The button shown in the attobot readme simply isn't there...

**Comment by KristofferC** [comment] 2017-06-06 06:42
Click on the release. Delete should be in the top right.

**Comment by andyferris** [comment] 2017-06-06 07:01
Thanks... I think I was in "edit". Silly me.

**Comment by andyferris** [comment] 2017-06-06 07:01
https://github.com/JuliaLang/METADATA.jl/pull/9679

**Comment by chriselrod** [comment] 2017-07-23 16:21
More broadcast weirdness:

```julia
using StaticArrays
mv = MVector{50}(randn(50))
x = rand(50);
mv .= log.(x)
all(mv .== log(x[1]))
```
Returns (and is) true, while
```julia
all(mv .== log.(x))
```
Returns (and is) false.

**Comment by mschauer** [comment] 2017-07-23 16:35
Which version are you using? Should this issue be reopened?

**Comment by chriselrod** [comment] 2017-07-23 16:42
I tried it on both 0.6.1 and master.

**Comment by c42f** [comment] 2017-07-23 23:45
Please open a new issue for this.
