### ISSUE TITLE
Broadcast should handle transpose of `StaticVector`

### ISSUE THREAD

**Issue by bshall** [JuliaArrays/StaticArrays.jl#200] opened 2017-05-29 15:51 UTC
If `x` is a `SVector` then `broadcast(f, x', ...)` should return a `StaticArray`. Currently the broadcasting falls back to Base except for broadcasts with a scalar. For example
```julia
x = SVector(1, 1)
1 .+ x'
```
returns a `RowVector{T, SVector{2, T}}`.

**Comment by andyferris** [comment] 2017-08-08 06:15
The behavior in the OP is intended.

We can't have that all statically-sized arrays are `<: StaticArray`. The `RowVector` code in `Base` is designed to be compatible with packages like `StaticArrays` (to wrap `RowVector` on the outside). Trait-based dispatch would help to express static-sizeness better...

However, the problem is that not all operations work on `RowVector{<:StaticArray}`. e.g.

```julia
julia 0.6> x = SVector(2,3)
2-element SVector{2,Int64}:
 2
 3

julia 0.6> x' .+ x
2×2 Array{Int64,2}:
 4  5
 5  6
```

We should look into this.

**Comment by wsshin** [comment] 2017-08-14 04:54
@bshall, this has been also resolved by https://github.com/JuliaArrays/StaticArrays.jl/pull/274.  Could you close this issue as well?

**Closed** 2017-08-14 05:09 UTC
