### ISSUE TITLE
broadcast! with non-static LHS broken on Julia master

### ISSUE THREAD

**Issue by tkoolen** [JuliaArrays/StaticArrays.jl#385] opened 2018-03-21 23:46 UTC
```julia
julia> using StaticArrays

julia> a = zeros(3, 3)
3×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> b = ones(SMatrix{3, 3})
3×3 SArray{Tuple{3,3},Float64,2,9}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

julia> a .= b
┌ Warning: Deprecated syntax `using the value of `.=``.
└ @ nothing none:0
ERROR: MethodError: Cannot `convert` an object of type Array{Float64,2} to an object of type Size
Closest candidates are:
  convert(::Type{T}, ::T) where T at essentials.jl:123
Stacktrace:
 [1] Size(::Array{Float64,2}) at ./deprecated.jl:472
 [2] broadcast! at /Users/twan/code/julia/RigidBodyDynamics/v0.7/StaticArrays/src/broadcast.jl:69 [inlined]
 [3] broadcast!(::typeof(identity), ::Array{Float64,2}, ::SArray{Tuple{3,3},Float64,2,9}) at ./broadcast.jl:444
 [4] top-level scope
```

**Comment by andyferris** [comment] 2018-03-22 02:41
What... is that deprecation warning?

Thanks for the report.

**Comment by fredrikekre** [comment] 2018-03-22 05:37
Likely a duplicate of https://github.com/JuliaLang/julia/issues/26516

**Comment by tkoolen** [comment] 2018-03-22 10:16
Yeah, the `.=` depwarn is rough. I'd be very surprised if that's still in place (at least at the repl, but even in general) upon release of 0.7. I'm imagining the `uninitialized` discussion on Discourse x10, all to support a pretty rare use case.

**Comment by tkoolen** [comment] 2018-03-22 19:35
I'll try to fix this one right now. Let me know if somebody else is already working on a fix.

**Closed** 2018-04-23 23:53 UTC
