### ISSUE TITLE
Product of SMatrix and Vector results in ambiguity

### ISSUE THREAD

**Issue by tkoolen** [JuliaArrays/StaticArrays.jl#54] opened 2016-10-26 16:57 UTC
Continuing from https://github.com/JuliaArrays/StaticArrays.jl/issues/25#issuecomment-256223775. I really appreciate the quick response, but unfortunately the new functionality doesn't seem to work as intended:

```julia
m = rand(SMatrix{3, 3})
v = rand(3)
m * v
```

now results in
```julia
ERROR: MethodError: *(::StaticArrays.SMatrix{3,3,Float64,9}, ::Array{Float64,1}) is ambiguous. Candidates:
  *(A::StaticArrays.StaticArray{T<:Any,2}, b::AbstractArray{T<:Any,1}) at /Users/twan/code/julia/RigidBodyDynamics/v0.5/StaticArrays/src/matrix_multiply.jl:136
  *{T<:Union{Complex{Float32},Complex{Float64},Float32,Float64},S}(A::Union{Base.ReshapedArray{T,2,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray{T,2},SubArray{T,2,A<:Union{Base.ReshapedArray{T<:Any,N<:Any,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N<:Any}},L<:Any}}, x::Union{Base.ReshapedArray{S,1,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray{S,1},SubArray{S,1,A<:Union{Base.ReshapedArray{T<:Any,N<:Any,A<:DenseArray,MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N<:Any}}},DenseArray},I<:Tuple{Vararg{Union{Base.AbstractCartesianIndex,Colon,Int64,Range{Int64}},N<:Any}},L<:Any}}) at linalg/matmul.jl:79
```

**Comment by andyferris** [comment] 2016-10-26 19:54
Oh bugger. This is BLAS-type specialization, in `Base`. I really should use @timholy's ambiguity tests.

I just tried fixing this, and this one seems *stubborn*. Grr.

**Comment by tkoolen** [comment] 2016-10-26 20:58
It's alright, I can just use my [quick hack](https://github.com/tkoolen/RigidBodyDynamics.jl/blob/c411ccc1c23213979eba2a0147f76678bec886c7/src/third_party_addendum.jl#L43) for now (overly specific, but good enough for my current purposes); perhaps some changes in `Base` are required to support this case elegantly.

**Comment by andyferris** [comment] 2016-10-26 22:54
I can fix the problem with `*`, but I'm having extreme difficulty from `A_mul_B!`

**Comment by andyferris** [comment] 2016-10-27 02:08
@tkoolen I looked at `RigidBodyDynamics.jl/src/third_party_addendum.jl` and just thought I'd mention that *Rotations.jl* has some nice quaternion rotations (plus more) that interoperate well with *StaticArrays*.

**Comment by tkoolen** [comment] 2016-10-27 02:37
Yeah, I'm considering it. See https://github.com/tkoolen/RigidBodyDynamics.jl/issues/87.

**Comment by andyferris** [comment] 2016-10-27 06:12
I think the ambiguities are fixed on master. Could you confirm for me @tkoolen and then I can tag and release.

**Comment by tkoolen** [comment] 2016-10-27 16:13
Yeah, the ambiguities are resolved in all of my use cases, thanks. However, I came across a different issue. With
```julia
m = rand(SMatrix{3, 3, Float32})
v = rand(Float64, 3)
```
`m * v` results in
```julia
3-element StaticArrays.SVector{3,Float32}:
 1.72883 
 0.990282
 0.288223
```
I was expecting the scalar type of the product to be `Float64`. In this example there's no error, but there is when the scalar type of `m` is e.g. `Float64` and the scalar type of `v` is `ForwardDiff.Dual` (this occurs in my package).

Always using the `else` branch of [this if-else block](https://github.com/JuliaArrays/StaticArrays.jl/blob/master/src/matrix_multiply.jl#L179) resolves the issue; I guess I don't quite understand why that if-else is necessary.

**Comment by andyferris** [comment] 2016-10-27 22:27
Thanks for catching that @tkoolen. The issue is fixed, and I'm [tagging it now](https://github.com/JuliaLang/METADATA.jl/pull/6888). I'll close the issue.

**Closed** 2016-10-27 22:27 UTC

**Comment by andyferris** [comment] 2016-10-27 22:33
I had that if-else because for certain custom types (e.g. where the element type parameter is fixed and not modifiable) you don't want to call `similar_type(SA, T)`  because that may return a different container type. I haven't implemented any such type but users can easily create any subtype of `StaticArray`, e.g. `FieldVector` may be relatively common.

In this case it's not particularly clear if that helps in many cases since we are changing the size and dimensionality. I'm thinking of implementing an improved system of type prediction and propagation.
