### ISSUE TITLE
SVector(0.0,0) throws an error

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaArrays/StaticArrays.jl#120] opened 2017-03-20 22:29 UTC
I would expect this to promote to `Float64`:

```julia
julia> SVector(0.,0)
ERROR: The size of type `StaticArrays.SVector` is not known.

If you were trying to construct (or `convert` to) a `StaticArray` you
may need to add the size explicitly as a type parameter so its size is
inferrable to the Julia compiler (or performance would be terrible). For
example, you might try

    m = zeros(3,3)
    SMatrix(m)      # this error
    SMatrix{3,3}(m) # correct - size is inferrable

Stacktrace:
 [1] StaticArrays.Size(::Type{StaticArrays.SVector}) at /Users/solver/.julia/v0.6/StaticArrays/src/traits.jl:42
 [2] StaticArrays.SVector(::Float64, ::Int64) at /Users/solver/.julia/v0.6/StaticArrays/src/core.jl:37
```

**Comment by dlfivefifty** [comment] 2017-03-20 22:29
This is only in 0.6

**Comment by andyferris** [comment] 2017-03-20 23:08
Can you try `Pkg.checkout("StaticArrays", "julia-0.6")` on v0.6, and see if the problem is gone?

(I haven't quite finished that branch, but it should have most basic functionality working)

**Comment by dlfivefifty** [comment] 2017-03-21 01:25
```julia
julia> Pkg.checkout("StaticArrays","julia-0.6")
INFO: Checking out StaticArrays julia-0.6...
INFO: Pulling StaticArrays latest julia-0.6...
WARNING: Cannot perform fast-forward merge.
INFO: No packages to install, update or remove

julia> using StaticArrays

julia> SVector(1.0,1)
ERROR: No precise constructor for StaticArrays.SVector found. Length of input was 2.
Stacktrace:
 [1] StaticArrays.SVector(::Float64, ::Int64) at /Users/solver/.julia/v0.6/StaticArrays/src/convert.jl:3
```

**Comment by dlfivefifty** [comment] 2017-03-21 01:25
So the error is slightly different

**Comment by andyferris** [comment] 2017-03-21 03:33
There was a missing `Any` in `NTuple{N, Any}` in one of the `SVector` constructors. In v0.6 this is distinct from `NTuple{N}` which asserts that the types are the same via `NTuple{N, T} where T` (with `T` concrete in covariant positions in a `UnionAll`). I'm fixing this on the `julia-0.6` branch, so I'll close the issue.

Thanks for reporting.

**Closed by andyferris** 2017-03-21 03:33 UTC
