### ISSUE TITLE
`inv`, `det`, etc. with SMatrix{2,2,T<:Unsigned}

### ISSUE THREAD

**Issue by ajkeller34** [JuliaArrays/StaticArrays.jl#29] opened 2016-09-12 22:43 UTC
I noticed the behavior is inconsistent between Base and StaticArrays when working with unsigned integers. I think it's probably an unchecked overflow issue that Base avoids with promotion or something.

```
julia> inv(@SMatrix [0x01 0x02; 0x02 0x01])
2×2 StaticArrays.SMatrix{2,2,Float64,4}:
 0.00395257  1.00395   
 1.00395     0.00395257

julia> inv([0x01 0x02; 0x02 0x01])
2×2 Array{Float64,2}:
 -0.333333   0.666667
  0.666667  -0.333333

julia> det([0x01 0x02; 0x02 0x01])
-3.0

julia> det(@SMatrix [0x01 0x02; 0x02 0x01])
0xfd

julia> versioninfo()
Julia Version 0.5.0-rc4+0
Commit 9c76c3e (2016-09-09 01:43 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by andyferris** [comment] 2016-09-12 23:54
Ummm... I'm not sure what to say, except that I've never thought to try that! Out of curiosity, why do you need this functionality?

I think the problem is the promotion rules in *StaticArrays* make the assumption that `+`, `-` and `*` return the same type. I'd like to fix this (or welcome a PR) and make more thorough use of `promote_op`.

**Comment by andyferris** [comment] 2016-11-15 02:41
I think I've worked around the issues with `det` and `inv` with `Unsigned on master, but I'll leave this open to remind me that promotion needs to be sensible elsewhere too.

**Comment by c42f** [comment] 2019-08-01 00:06
I think we've sorted this out a long while back; let's close it off.

**Closed by c42f** 2019-08-01 00:06 UTC
