### ISSUE TITLE
exp() test failures on Julia nightly

### ISSUE THREAD

**Issue by c42f** [JuliaArrays/StaticArrays.jl#849] opened 2020-11-04 12:42 UTC
I've just spotted a new failure on 1.6-DEV which doesn't appear in 1.5.

Explicit example extracted from one of the test/expm.jl cases

```julia
julia> exp(SA[0.0003616311661896927 0.02414126283180501 0.020091615785305276; 0.0005711647100532968 0.006369723295446879 0.01919452039427785; 0.007626623842418941 0.01342122254626238 0.008222235428240684])
ERROR: MethodError: no method matching length(::UniformScaling{Float64})
Closest candidates are:
  length(::Union{Base.KeySet, Base.ValueIterator}) at abstractdict.jl:54
  length(::Union{Adjoint{T, var"#s6"} where var"#s6"<:Union{StaticVector{var"#s1", T} where var"#s1", StaticMatrix{var"#s4", var"#s5", T} where var"#s5" where var"#s4"}, Diagonal{T, var"#s13"} where var"#s13"<:(StaticVector{var"#s14", T} where var"#s14"), Hermitian{T, var"#s10"} where var"#s10"<:(StaticMatrix{var"#s11", var"#s12", T} where var"#s12" where var"#s11"), LowerTriangular{T, var"#s18"} where var"#s18"<:(StaticMatrix{var"#s19", var"#s20", T} where var"#s20" where var"#s19"), Symmetric{T, var"#s7"} where var"#s7"<:(StaticMatrix{var"#s8", var"#s9", T} where var"#s9" where var"#s8"), Transpose{T, var"#s1"} where var"#s1"<:Union{StaticVector{var"#s1", T} where var"#s1", StaticMatrix{var"#s4", var"#s5", T} where var"#s5" where var"#s4"}, UnitLowerTriangular{T, var"#s24"} where var"#s24"<:(StaticMatrix{var"#s25", var"#s26", T} where var"#s26" where var"#s25"), UnitUpperTriangular{T, var"#s21"} where var"#s21"<:(StaticMatrix{var"#s22", var"#s23", T} where var"#s23" where var"#s22"), UpperTriangular{T, var"#s15"} where var"#s15"<:(StaticMatrix{var"#s16", var"#s17", T} where var"#s17" where var"#s16"), StaticVector{var"#s26", T} where var"#s26", StaticMatrix{var"#s5", var"#s4", T} where var"#s4" where var"#s5", StaticArray{var"#s26", T, N} where N where var"#s26"<:Tuple} where T) at /home/chris/.julia/dev/StaticArrays/src/abstractarray.jl:1
  length(::Union{Adjoint{T, S}, Transpose{T, S}} where S where T) at /home/chris/dev/julia/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/adjtrans.jl:194
  ...
Stacktrace:
  [1] _similar_for(c::UnitRange{Int64}, #unused#::Type{Float64}, itr::UniformScaling{Float64}, #unused#::Base.HasLength)
    @ Base ./array.jl:575
  [2] _collect(cont::UnitRange{Int64}, itr::UniformScaling{Float64}, #unused#::Base.HasEltype, isz::Base.HasLength)
    @ Base ./array.jl:608
  [3] collect(itr::UniformScaling{Float64})
    @ Base ./array.jl:602
  [4] broadcastable(x::UniformScaling{Float64})
    @ Base.Broadcast ./broadcast.jl:682
  [5] broadcasted
    @ ./broadcast.jl:1303 [inlined]
  [6] muladd(A::SMatrix{3, 3, Float64, 9}, B::SMatrix{3, 3, Float64, 9}, z::UniformScaling{Float64})
    @ LinearAlgebra ~/dev/julia/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/matmul.jl:214
  [7] macro expansion
    @ ./math.jl:123 [inlined]
  [8] evalpoly(x::SMatrix{3, 3, Float64, 9}, p::Tuple{UniformScaling{Float64}, UniformScaling{Float64}, UniformScaling{Float64}})
    @ Base.Math ./math.jl:122
  [9] _exp(#unused#::Size{(3, 3)}, _A::SMatrix{3, 3, Float64, 9})
    @ StaticArrays ~/.julia/dev/StaticArrays/src/expm.jl:85
 [10] exp(A::SMatrix{3, 3, Float64, 9})
    @ StaticArrays ~/.julia/dev/StaticArrays/src/expm.jl:1
 [11] top-level scope
    @ REPL[24]:1
```

**Comment by mateuszbaran** [comment] 2020-11-04 13:36
Here is the cause: https://github.com/JuliaLang/julia/pull/37065 .

**Comment by c42f** [comment] 2020-11-05 03:55
Thanks! Looks like this may be fixed by https://github.com/JuliaLang/julia/pull/38250 then.

**Comment by hyrodium** [comment] 2021-07-22 08:48
```julia
julia> using StaticArrays

julia> exp(SA[0.0003616311661896927 0.02414126283180501 0.020091615785305276; 0.0005711647100532968 0.006369723295446879 0.01919452039427785; 0.007626623842418941 0.01342122254626238 0.008222235428240684])
3×3 SMatrix{3, 3, Float64, 9} with indices SOneTo(3)×SOneTo(3):
 1.00045      0.0243599  0.0204124
 0.000646695  1.00653    0.0193422
 0.00766384   0.013613   1.00846
```

This problem seems solved, so we can close this issue.

**Closed** 2021-07-22 13:33 UTC
Labels: fix-in-base
