### ISSUE TITLE
C error leaking into StaticArrays code

### ISSUE THREAD

**Issue by dpsanders** [JuliaArrays/StaticArrays.jl#117] opened 2017-03-18 00:42 UTC
Testing the latest release of `IntervalConstraintProgramming` with the latest release of `ValidatedNumerics`, which just changed from `FixedSizeArrays` to `StaticArrays`,  I get the following C error leaking into my Julia code. This seems to be related to StaticArrays.jl:
```
julia v0.5> Pkg.test("IntervalConstraintProgramming")
INFO: Computing test dependencies for IntervalConstraintProgramming...
INFO: No packages to install, update or remove
INFO: Testing IntervalConstraintProgramming
Test Summary: | Pass  Total
  Utilities   |    1      1
Test Summary: | Pass  Total
  Contractor  |    1      1
Test Summary: | Pass  Total
  Separators  |    5      5

signal (4): Illegal instruction: 4
while loading /Users/dpsanders/.julia/v0.5/IntervalConstraintProgramming/test/runtests.jl, in expression starting on line 45
pave at /Users/dpsanders/.julia/v0.5/IntervalConstraintProgramming/src/setinversion.jl:36
pave at /Users/dpsanders/.julia/v0.5/IntervalConstraintProgramming/src/setinversion.jl:54
unknown function (ip: 0x316bb71c1)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:210 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1950
macro expansion; at /Users/dpsanders/.julia/v0.5/IntervalConstraintProgramming/test/runtests.jl:50 [inlined]
macro expansion; at ./test.jl:674 [inlined]
anonymous at ./<missing> (unknown line)
unknown function (ip: 0x316bb5c3f)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:210 [inlined]
jl_toplevel_eval_flex at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:569
jl_parse_eval_all at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/ast.c:717
jl_load at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:596 [inlined]
jl_load_ at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/toplevel.c:605
include_from_node1 at ./loading.jl:488
jlcall_include_from_node1_20312 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:210 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1950
process_options at ./client.jl:265
_start at ./client.jl:321
jlcall__start_21657 at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_call_method_internal at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/./julia_internal.h:210 [inlined]
jl_apply_generic at /Users/osx/buildbot/slave/package_osx10_9-x64/build/src/gf.c:1950
true_main at /Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia (unknown line)
main at /Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia (unknown line)
Allocations: 5488282 (Pool: 5487186; Big: 1096); GC: 7
====================[ ERROR: IntervalConstraintProgramming ]====================

failed process: Process(`/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /Users/dpsanders/.julia/v0.5/IntervalConstraintProgramming/test/runtests.jl`, ProcessSignaled(4)) [0]

================================================================================
INFO: No packages to install, update or remove
------ PkgError ------------------------ Stacktrace (most recent call last)

 [1] — test(::String, ::Vararg{String,N}) at pkg.jl:258

 [2] — #test#3(::Bool, ::Function, ::String, ::Vararg{String,N}) at pkg.jl:258

 [3] — (::Base.Pkg.Dir.#kw##cd)(::Array{Any,1}, ::Base.Pkg.Dir.#cd, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at <missing>:0

 [4] — #cd#1(::Array{Any,1}, ::Function, ::Function, ::Array{AbstractString,1}, ::Vararg{Array{AbstractString,1},N}) at dir.jl:31

 [5] — cd(::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}}, ::String) at file.jl:59

 [6] — (::Base.Pkg.Dir.##2#3{Array{Any,1},Base.Pkg.Entry.#test,Tuple{Array{AbstractString,1}}})() at dir.jl:31

 [7] — (::Base.Pkg.Entry.#kw##test)(::Array{Any,1}, ::Base.Pkg.Entry.#test, ::Array{AbstractString,1}) at <missing>:0

 [8] — #test#61(::Bool, ::Function, ::Array{AbstractString,1}) at entry.jl:749

IntervalConstraintProgramming had test errors
```

**Comment by SimonDanisch** [comment] 2017-03-18 10:38
Would be nice to have some more information ;) 
Can you reduce it to something reproducable?

**Comment by dpsanders** [comment] 2017-03-18 15:30
I'm working on it!

**Comment by dpsanders** [comment] 2017-03-22 14:59
This seems to be fixed on 0.6 with the `julia-0.6` branch.

**Comment by andyferris** [comment] 2017-03-24 05:55
Is this an issue on 0.5? Or can we close this?

**Comment by tkelman** [comment] 2017-03-24 07:24
This is an issue on 0.5. http://pkg.julialang.org/logs/IntervalConstraintProgramming_0.5.log

**Comment by dpsanders** [comment] 2017-03-24 14:00
This still occurs on 0.5, even with the julia-0.6 branch. It seems to be some kind of inference issue that happens only inside a `@testset`. (The code runs fine outside a `@testset`.)

**Comment by andyferris** [comment] 2017-04-01 23:02
Regarding strange `@testset` errors - this maybe unrelated, but I had problems like this when reusing variables and populating them with different types within the same scope. I could never make a MWE but sometimes when I overrode `m`, say, with dozens of different matrix types within the one testset, I would get bad problems like this one (caused by inference getting confused somehow, as I understood).

**Comment by c42f** [comment] 2019-07-31 23:37
Closing - times have moved on from 0.5 :-)

**Closed by c42f** 2019-07-31 23:37 UTC
