### ISSUE TITLE
Outer product return type change with non-Real scalar types

### ISSUE THREAD

**Issue by tkoolen** [JuliaArrays/StaticArrays.jl#156] opened 2017-05-05 04:28 UTC
On StaticArrays 0.3.0 (Julia 0.5.1),
```julia
using StaticArrays
x = zero(SVector{3, Number})
x * x'
```
results in
```
3×3 StaticArrays.SMatrix{3,3,Int64,9}:
 0  0  0
 0  0  0
 0  0  0
```
while on StaticArrays 0.5.0 (latest Julia nightly) it results in
```
3×3 Array{Int64,2}:
 0  0  0
 0  0  0
 0  0  0
```
because the generic
```
*(vec::AbstractArray{T,1} where T, rowvec::RowVector) in Base.LinAlg at linalg/rowvector.jl:183
```
is called.
The scalar type (`Number` above) doesn't have to be abstract; I ran into this with the concrete `SymPy.Sym` type.

**Comment by andyferris** [comment] 2017-05-05 04:49
The problem isn't the abstract type, it is that it isn't `Real`. I forgot to add `*(::StaticVector, ::Base.LinAlg.ConjRowVector)`. (I should have known better... I authored `ConjRowVector`...)

**Comment by tkoolen** [comment] 2017-05-05 05:00
Ah, that's it, sorry.

**Comment by andyferris** [comment] 2017-05-05 05:37
I've got a fix for this too

**Closed** 2017-05-11 01:11 UTC
