### ISSUE TITLE
Error returning eltype of SMatrix

### ISSUE THREAD

**Issue by getzze** [JuliaArrays/StaticArrays.jl#423] opened 2018-05-30 17:33 UTC
Testing package `GLVisualize.jl`, I got an error in `GLAbstarction.jl` (https://github.com/JuliaGL/GLAbstraction.jl/blob/master/src/GLMatrixMath.jl). The error is:

`LoadError: TypeError: UnionAll: expected Type, got Int64`

It points to this function in `GLMatrixMath.jl`:
```
function (::Type{M})(q::Quaternions.Quaternion) where M <: Mat{3}
    T = eltype(M)
    sx, sy, sz = 2q.s*q.v1, 2q.s*q.v2,  2q.s*q.v3
    xx, xy, xz = 2q.v1^2,   2q.v1*q.v2, 2q.v1*q.v3
    yy, yz, zz = 2q.v2^2,   2q.v2*q.v3, 2q.v3^2
    T0, T1 = zero(T), one(T)
    Mat{3}(
        T1-(yy+zz), xy+sz,      xz-sy,
        xy-sz,      T1-(xx+zz), yz+sx,
        xz+sy,      yz-sx,      T1-(xx+yy)
    )
end
```

I figured out that checking the element type of some SMatrix gives me the same error:
```
eltype(Mat{3,3,Int, 9})  # Int64
eltype(Mat{3,3,Int})  # TypeError: UnionAll: expected Type, got Int64
eltype(Mat{3,Int})  # TypeError: UnionAll: expected Type, got Int64
eltype(Mat{Int})  # Any
eltype(Mat{3})  # TypeError: UnionAll: expected Type, got Int64
```

Is it related to the error in `GLAbstarction.jl`?

**Comment by tkoolen** [comment] 2018-05-30 17:40
I can't reproduce with Julia 0.6.2 (or master) and StaticArrays master:

```julia
julia> using StaticArrays.FixedSizeArrays

julia> eltype(Mat{3,3,Int, 9})  # Int64
Int64

julia> eltype(Mat{3,3,Int})  # TypeError: UnionAll: expected Type, got Int64
Int64

julia> eltype(Mat{3,Int})  # TypeError: UnionAll: expected Type, got Int64
Any

julia> eltype(Mat{Int})  # Any
Any

julia> eltype(Mat{3})  # TypeError: UnionAll: expected Type, got Int64
Any
```

**Comment by getzze** [comment] 2018-06-04 11:15
I'm using Julia 0.6.3 on ArchLinux. With a fresh start of julia (without loading any module), I get:
```
julia> using StaticArrays.FixedSizeArrays

julia> eltype(Mat{3,3,Int, 9})  # Int64
Int64

julia> eltype(Mat{3,3,Int})  # TypeError: UnionAll: expected Type, got Int64
Int64

julia> eltype(Mat{3,Int})  # TypeError: UnionAll: expected Type, got Int64
ERROR: TypeError: UnionAll: expected Type, got Int64

julia> eltype(Mat{Int})  # Any
ERROR: TypeError: UnionAll: expected Type, got Int64

julia> eltype(Mat{3})  # TypeError: UnionAll: expected Type, got Int64
Any

julia> eltype(Mat{3,3})
Any

```

I don't remember which modules were loaded last time, so I cannot reproduce. I still cannot load GLAbstraction.js though.

**Comment by tkoolen** [comment] 2018-06-04 13:13
On 0.6.3 with StaticArrays master I can now reproduce the behavior in https://github.com/JuliaArrays/StaticArrays.jl/issues/423#issuecomment-394319289. `Mat{3,Int}` and `Mat{Int}` don't really make sense though (the first two type parameters should be integer values). The other ones produce the correct results, so I'm not sure if this is actionable.

I guess a better error message would be nice, but Julia currently has no way of expressing the constraint that a type parameter should be an integer value (e.g. `3`), so in order to provide a better error message when methods are called on StaticArrays `Type`s with 'nonsensical' type parameters, a check would need to be added to every such method.

By the way, the method in the issue description is technically type piracy. But in general, if you want to be able to write `Mat{3}(q)`, you should probably define something like

```julia
function Mat{3}(q::Quaternions.Quaternion{T}) where {T}
    sx, sy, sz = 2q.s*q.v1, 2q.s*q.v2,  2q.s*q.v3
    xx, xy, xz = 2q.v1^2,   2q.v1*q.v2, 2q.v1*q.v3
    yy, yz, zz = 2q.v2^2,   2q.v2*q.v3, 2q.v3^2
    T0, T1 = zero(T), one(T)
    Mat{3}(
        T1-(yy+zz), xy+sz,      xz-sy,
        xy-sz,      T1-(xx+zz), yz+sx,
        xz+sy,      yz-sx,      T1-(xx+yy)
    )
end
```

Also note that [Rotations.jl](https://github.com/FugroRoames/Rotations.jl) exists, is built on top of `StaticArrays`, and already has this functionality and a lot more.

**Comment by KristofferC** [comment] 2018-06-04 13:15
Probably fixed by https://github.com/JuliaLang/julia/pull/27404.

**Comment by getzze** [comment] 2018-06-04 14:09
Ok, thanks a lot! I will report to the GLAbstraction.jl package maintainer.

**Comment by c42f** [comment] 2019-07-31 10:54
This has long since been sorted out elsewhere I think.

**Closed by c42f** 2019-07-31 10:54 UTC
