### ISSUE TITLE
result type of operations on Static and non-Static arrays

### ISSUE THREAD

**Issue by goretkin** [JuliaArrays/StaticArrays.jl#576] opened 2018-12-22 02:59 UTC
On `[90137ffa] StaticArrays v0.10.0`, I get

```
julia> (@SMatrix  [1 2; 3 4]) * [1 2]' 
2×1 Array{Int64,2}:
  5
 11

julia> (@SMatrix  [1 2; 3 4]) * [1, 2]
2-element SArray{Tuple{2},Int64,1,2}:
  5
 11
```

I think I prefer the first kind of behavior over the second, that matrices operate on vectors, and the type of the vector (up to element type, and dimension) should be preserved. But in any case, it seems like both of the operations should either return an `SArray`, or an `Array`

**Comment by goretkin** [comment] 2018-12-22 08:52
Do you rely on the second case in user-facing interfaces (to allow a user,
for convenience, to pass a non-static array), or is there another dynamic
"entry point"?

I see what you mean, that the full size is not determined by the types.
However, when it becomes possible to have static and dynamic dimensions, it
would be possible to determine one of the two dimensions. Would you prefer
that as well?

"Be as static as possible." is a valid principle, which I hadn't
considered. Thanks. But it does mean in this case that 'StaticMatrix'
cannot be a drop-in replacement in a function that, for example, multiplies
a vector by a matrix and then mutates it. This might be a more general
problem, though, of doing generic programming over mutable and immutable
types.

**Comment by c42f** [comment] 2018-12-22 12:11
@tkoolen is spot on here. (`[1 2]'` being a 2x1 AbstractMatrix rather than an AbstractVector, we can't deduce the second dimension of the multiplication output at compile time).

Also about the "static as possible" heuristic, this is a good way to think about what you get from this package. The reasoning here is that users should generally only make a dimension static when it's "sufficiently small", such that they expect to get a performance benefit. Thus we respect their decision in carrying that statically sized dimension through the calculation rather than dropping it half way along.

> However, when it becomes possible to have static and dynamic dimensions, it would be possible to determine one of the two dimensions. Would you prefer that as well? 

I think this would make sense. Perhaps one day we could produce a `SizedMatrix{Tuple{2,Dynamic()}, ...}` from that first multiplication. I'm not sure how hard this is to implement yet.

> But it does mean in this case that 'StaticMatrix' cannot be a drop-in replacement in a function that, for example, multiplies a vector by a matrix and then mutates it

Yes it's an unsolved problem about how to write generic code which both makes efficient use of memory (preferring mutating algorithms) and works for immutable array types (which seem to need a functional style). Though you can pass `MMatrix` to packages which optimize for the former case and assume mutability; static sizing and mutability are definitely not the same thing.

**Comment by c42f** [comment] 2018-12-22 12:13
I'll close this issue as I think everything is behaving as designed here. Though admittedly the results are confusing at first sight.

**Closed by c42f** 2018-12-22 12:13 UTC

**Comment by c42f** [comment] 2018-12-22 13:36
> Do you rely on the second case in user-facing interfaces (to allow a user, for convenience, to pass a non-static array), or is there another dynamic "entry point"?

I don't think I understand this part of your comment, by the way. Perhaps you could give an example.

**Comment by goretkin** [comment] 2019-01-07 07:43
@c42f sorry for the delayed reply. I agree this issue can be closed.


> > Do you rely on the second case in user-facing interfaces (to allow a user, for convenience, to pass a non-static array), or is there another dynamic "entry point"?
> 
> I don't think I understand this part of your comment, by the way. Perhaps you could give an example.

I was curious where users of StaticArrays (like @tkoolen) were relying on this "as static as possible" behavior. Where were dynamic arrays coming from?

In my case, roughly, I had some quick-and-dirty code doing small matvec multiplies. The user of some function provided provided a vector, the function returned the multiplied vector. I wanted to drop-in replace the matrix `Array` with a `StaticArray`, but this broke the user of the function, because the returned vector was a different type.

So, in this case, the user passed in an `Array`, and I preferred to return an `Array`. If the user doesn't know about StaticArrays to pass me one, then at least I'll use StaticArrays to do some loop unrolling (or whatever), but I won't return one to the user. That was the reason I preferred the first behavior in my original comment.

I imagined that the "as static as possible" behavior might be preferred if you're about to enter a _totally static ecosystem_ but you want to allow your user to pass in an `Array`.

Hopefully I only clarified what I intended to say.

**Comment by goretkin** [comment] 2019-01-07 19:52
It's not that I wanted to be sure to return an `Array`. I wanted to be sure
to return the input vector type. But I'm already convinced the behavior
should stay.

Still, my question had to do with where your `::Vector` is coming from in
the first place, and why it isn't already a `StaticArray` type.
