### ISSUE TITLE
Infinite loop when broadcasting between Array and SArray

### ISSUE THREAD

**Issue by traktofon** [JuliaArrays/StaticArrays.jl#411] opened 2018-05-22 13:21 UTC
To reproduce:

```julia
using StaticArrays
a = [0,1]
b = @SVector [1,2,3]
a .* b'
```

Julia hangs at the prompt, consumes 100% CPU and increasing amounts of memory. When interrupted, a very long backtrace is printed which points to an infinite loop:
```
...
 [52316] broadcast_indices(::RowVector{Int64,StaticArrays.SArray{Tuple{3},Int64,1,3}}) at ./broadcast.jl:48
 [52317] broadcast_indices(::Type{T} where T, ::RowVector{Int64,StaticArrays.SArray{Tuple{3},Int64,1,3}}) at ./broadcast.jl:53
 [52318] broadcast_indices(::RowVector{Int64,StaticArrays.SArray{Tuple{3},Int64,1,3}}) at ./broadcast.jl:48
 [52319] broadcast_indices(::Type{T} where T, ::RowVector{Int64,StaticArrays.SArray{Tuple{3},Int64,1,3}}) at ./broadcast.jl:53
 [52320] broadcast_indices(::RowVector{Int64,StaticArrays.SArray{Tuple{3},Int64,1,3}}) at ./broadcast.jl:48
 ...
```

If `a` and `b` are both `Vector`s or `SVector`s, the operation succeeds without issue.

Version information:
```
julia> Pkg.installed("StaticArrays")
v"0.7.0

julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU           E5430  @ 2.66GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Penryn)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, penryn)
```

**Comment by tkoolen** [comment] 2018-05-22 16:49
Duplicate of https://github.com/JuliaArrays/StaticArrays.jl/issues/382. Fixed on master. We need a new version tag.

**Comment by andyferris** [comment] 2018-05-22 23:41
OK lets just do it :)

**Comment by andyferris** [comment] 2018-05-22 23:45
Version 0.7.1 should be incoming... go Attobot, go!

**Closed by andyferris** 2018-05-22 23:45 UTC
